-- Nordic starter seed for AI educators
-- Kjor etter: supabase/ai-educators-2026-02-22.sql
-- Denne filen er laget for rask testing i SQL Editor.

with educators_seed (
  slug,
  name,
  platform,
  url,
  niche,
  update_frequency,
  free_content_score,
  transparency_score,
  depth_score,
  hype_level,
  commercial_bias_score,
  language,
  region,
  platform_handle,
  notes,
  last_checked,
  is_active
) as (
  values
    (
      'eirik-solheim',
      'Eirik Solheim',
      'linkedin',
      'https://www.linkedin.com/in/eiriksolheim/',
      'general',
      'multi_weekly',
      88,
      86,
      82,
      24,
      20,
      'no',
      'norway',
      '@eiriksolheim',
      'Deler praktiske AI-eksempler og tydelige arbeidsmetoder.',
      now(),
      true
    ),
    (
      'morten-goodwin',
      'Morten Goodwin',
      'website',
      'https://www.uia.no/om-uia/ansatte/mortengo',
      'strategy',
      'weekly',
      82,
      91,
      92,
      18,
      12,
      'no',
      'norway',
      null,
      'Forskningsdrevet formidling med hoy troverdighet.',
      now(),
      true
    ),
    (
      'inga-strumke',
      'Inga Strumke',
      'website',
      'https://www.ntnu.no/ansatte/inga.strumke',
      'strategy',
      'biweekly',
      80,
      89,
      90,
      20,
      15,
      'no',
      'norway',
      null,
      'Sterk pa forklaring av AI i offentlig og kommersiell kontekst.',
      now(),
      true
    ),
    (
      'alexandra-instituttet',
      'Alexandra Instituttet',
      'website',
      'https://alexandra.dk/',
      'automation',
      'weekly',
      78,
      84,
      86,
      22,
      30,
      'da',
      'nordic',
      null,
      'Anvendt AI-kompetanse, testlab og kunnskapsdeling for industri.',
      now(),
      true
    ),
    (
      'digitaliseringsdirektoratet',
      'Digitaliseringsdirektoratet',
      'website',
      'https://www.digdir.no/',
      'general',
      'weekly',
      76,
      88,
      80,
      16,
      8,
      'no',
      'norway',
      null,
      'Apen veiledning, webinarer og rammer for ansvarlig AI-bruk.',
      now(),
      true
    )
)
insert into public.ai_educators (
  slug,
  name,
  platform,
  url,
  niche,
  update_frequency,
  free_content_score,
  transparency_score,
  depth_score,
  hype_level,
  commercial_bias_score,
  language,
  region,
  platform_handle,
  notes,
  last_checked,
  is_active
)
select
  slug,
  name,
  platform,
  url,
  niche,
  update_frequency,
  free_content_score,
  transparency_score,
  depth_score,
  hype_level,
  commercial_bias_score,
  language,
  region,
  platform_handle,
  notes,
  last_checked,
  is_active
from educators_seed
on conflict (slug) do update
set
  name = excluded.name,
  platform = excluded.platform,
  url = excluded.url,
  niche = excluded.niche,
  update_frequency = excluded.update_frequency,
  free_content_score = excluded.free_content_score,
  transparency_score = excluded.transparency_score,
  depth_score = excluded.depth_score,
  hype_level = excluded.hype_level,
  commercial_bias_score = excluded.commercial_bias_score,
  language = excluded.language,
  region = excluded.region,
  platform_handle = excluded.platform_handle,
  notes = excluded.notes,
  last_checked = excluded.last_checked,
  is_active = excluded.is_active,
  updated_at = now();

with updates_seed (
  educator_slug,
  external_id,
  platform,
  content_type,
  title,
  description,
  url,
  published_at,
  view_count,
  like_count,
  comment_count,
  keyword_tags,
  signal_depth,
  signal_hype,
  signal_transparency,
  notes,
  is_active
) as (
  values
    (
      'eirik-solheim',
      'li:eirik-solheim-profile',
      'linkedin',
      'post',
      'Praktisk AI-bruk i innholdsproduksjon',
      'Startpost for kuratert norsk educator-feed.',
      'https://www.linkedin.com/in/eiriksolheim/',
      '2026-01-15T09:00:00Z'::timestamptz,
      null,
      null,
      null,
      array['workflow', 'norsk', 'kreativ-ai'],
      78,
      18,
      84,
      'Seedet manuelt.',
      true
    ),
    (
      'morten-goodwin',
      'web:morten-goodwin-uia',
      'website',
      'article',
      'Faglig AI-formidling med forskningsforankring',
      'Profilrad for strategisk og faktabasert oppdateringsspor.',
      'https://www.uia.no/om-uia/ansatte/mortengo',
      '2026-01-08T10:00:00Z'::timestamptz,
      null,
      null,
      null,
      array['strategi', 'forskning', 'norge'],
      88,
      12,
      90,
      'Seedet manuelt.',
      true
    ),
    (
      'inga-strumke',
      'web:inga-strumke-ntnu',
      'website',
      'article',
      'Forklarbar AI i praksis',
      'Profilrad for offentlig og kommersiell kunnskapsdeling.',
      'https://www.ntnu.no/ansatte/inga.strumke',
      '2026-01-04T11:00:00Z'::timestamptz,
      null,
      null,
      null,
      array['forklarbar-ai', 'offentlig', 'norge'],
      86,
      14,
      90,
      'Seedet manuelt.',
      true
    ),
    (
      'alexandra-instituttet',
      'web:alexandra-home',
      'website',
      'article',
      'Anvendt AI for virksomheter',
      'Profilrad for nordisk lab- og industrinara kunnskapsdeling.',
      'https://alexandra.dk/',
      '2026-01-10T08:00:00Z'::timestamptz,
      null,
      null,
      null,
      array['automation', 'nordic', 'applied-ai'],
      82,
      20,
      84,
      'Seedet manuelt.',
      true
    ),
    (
      'digitaliseringsdirektoratet',
      'web:digdir-home',
      'website',
      'article',
      'Retningslinjer og veiledning for ansvarlig AI',
      'Profilrad for offentlige ressurser og webinarspor.',
      'https://www.digdir.no/',
      '2026-01-12T07:30:00Z'::timestamptz,
      null,
      null,
      null,
      array['offentlig-sektor', 'governance', 'norge'],
      80,
      10,
      88,
      'Seedet manuelt.',
      true
    )
)
insert into public.ai_educator_updates (
  educator_id,
  external_id,
  platform,
  content_type,
  title,
  description,
  url,
  published_at,
  view_count,
  like_count,
  comment_count,
  keyword_tags,
  signal_depth,
  signal_hype,
  signal_transparency,
  notes,
  is_active
)
select
  e.id,
  s.external_id,
  s.platform,
  s.content_type,
  s.title,
  s.description,
  s.url,
  s.published_at,
  s.view_count,
  s.like_count,
  s.comment_count,
  s.keyword_tags,
  s.signal_depth,
  s.signal_hype,
  s.signal_transparency,
  s.notes,
  s.is_active
from updates_seed s
join public.ai_educators e on e.slug = s.educator_slug
on conflict (educator_id, external_id) do update
set
  platform = excluded.platform,
  content_type = excluded.content_type,
  title = excluded.title,
  description = excluded.description,
  url = excluded.url,
  published_at = excluded.published_at,
  view_count = excluded.view_count,
  like_count = excluded.like_count,
  comment_count = excluded.comment_count,
  keyword_tags = excluded.keyword_tags,
  signal_depth = excluded.signal_depth,
  signal_hype = excluded.signal_hype,
  signal_transparency = excluded.signal_transparency,
  notes = excluded.notes,
  is_active = excluded.is_active,
  updated_at = now();
